version: 0.2
phases:
  install:
    commands:
    - echo "install step"
  pre_build:
    commands:
    - echo "pre_build step"
  build:
    commands:
    - aws s3 sync . "s3://website-gawn-subdomain-cc" --exclude buildspec.yml --exclude main.tf --exclude ".gitignore" --exclude "*.md" --exclude ".idea/*" --exclude ".git/*" --delete
  post_build:
    commands:
    - echo "post_build step"